In [6]:
a = 3
type(a)

int

In [7]:
a.bit_length()

2

In [9]:
print((3).bit_length())

2


In [11]:
b=5.
type(b)

float

In [12]:
c = 10**100
c

10000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000

In [13]:
c.bit_length()

333

In [14]:
3/5.

0.6

In [15]:
a*b

15.0

In [16]:
import math

In [17]:
math.log(a)

1.0986122886681098

In [18]:
math.exp(a)

20.085536923187668

In [19]:
math.sin(b)

-0.9589242746631385

In [20]:
print(math.e)

2.718281828459045


In [21]:
print(math.pi)

3.141592653589793


In [22]:
print(math.sin(0))

0.0


In [23]:
print(math.sin(math.pi/2))

1.0


In [24]:
s = 'Python for Algorithmic Trading.'
type(s)

str

In [25]:
s.lower()

'python for algorithmic trading.'

In [26]:
s.upper()

'PYTHON FOR ALGORITHMIC TRADING.'

In [27]:
s[0:6]

'Python'

In [29]:
st = s[0:6] + s[-9:-1]
print(st)

Python Trading


In [30]:
repl = 'My name is %s, I am %d years old and %4.2f m tall.'
print(repl % ('Gordon Gekko', 42, 1.78))

My name is Gordon Gekko, I am 42 years old and 1.78 m tall.


In [32]:
repl = 'My name is {:s}, I am {:d} years old and {:4.2f} m tall. '
print(repl.format('Gordon Gekko', 42, 1.78))


My name is Gordon Gekko, I am 42 years old and 1.78 m tall. 


In [34]:
name, age, height = 'Gordon Gekko', 43, 1.78
print(f'My name is {name:s}, I am {age:d} years old, and \ {height:4.2f}m tall.')

My name is Gordon Gekko, I am 43 years old, and \ 1.78m tall.


<>:2: SyntaxWarning: invalid escape sequence '\ '
<>:2: SyntaxWarning: invalid escape sequence '\ '
C:\Users\User\AppData\Local\Temp\ipykernel_35148\782732499.py:2: SyntaxWarning: invalid escape sequence '\ '
  print(f'My name is {name:s}, I am {age:d} years old, and \ {height:4.2f}m tall.')


In [36]:
ticker = "NAS100"
profit = 12.3456

print("Ticker: %s, Profit: %.2f%%" % (ticker, profit))

Ticker: NAS100, Profit: 12.35%


In [37]:
print("Ticker: {}, Profit: {:.2f}%".format(ticker, profit))

Ticker: NAS100, Profit: 12.35%


In [39]:
print(f"Ticker: {ticker}, Profit: {profit:.2f}%")

Ticker: NAS100, Profit: 12.35%


In [40]:
t1 = (a, b, st)
t1

(3, 5.0, 'Python Trading')

In [41]:
type(t1)

tuple

In [42]:
t2 = st, b, a 
t2

('Python Trading', 5.0, 3)

In [44]:
type(t2)

tuple

In [45]:
t = (t1, t2)
t

((3, 5.0, 'Python Trading'), ('Python Trading', 5.0, 3))

In [46]:
t[0][2]

'Python Trading'

In [47]:
l = [a, b, st]
l

[3, 5.0, 'Python Trading']

In [48]:
type(1)

int

In [49]:
type(l)

list

In [50]:
l.append(s.split()[3])

In [51]:
l

[3, 5.0, 'Python Trading', 'Trading.']

In [52]:
l = list(('Z', 'Q', 'D', 'J', 'E', 'H', '5.', 'a'))

In [53]:
l

['Z', 'Q', 'D', 'J', 'E', 'H', '5.', 'a']

In [54]:
l.sort()

In [55]:
l

['5.', 'D', 'E', 'H', 'J', 'Q', 'Z', 'a']

In [56]:
d = {'int_obj': a, 'float_obj': b, 'string_obj':st}

In [57]:
type(d)

dict

In [58]:
d

{'int_obj': 3, 'float_obj': 5.0, 'string_obj': 'Python Trading'}

In [59]:
d['float_obj']

5.0

In [60]:
d['int_obj_long'] = 10**20 

In [61]:
d

{'int_obj': 3,
 'float_obj': 5.0,
 'string_obj': 'Python Trading',
 'int_obj_long': 100000000000000000000}

In [62]:
d.keys()

dict_keys(['int_obj', 'float_obj', 'string_obj', 'int_obj_long'])

In [63]:
d.values()

dict_values([3, 5.0, 'Python Trading', 100000000000000000000])

In [64]:
range(5)

range(0, 5)

In [65]:
range(3, 15, 2)

range(3, 15, 2)

In [66]:
for i in range(5)

SyntaxError: expected ':' (1674873758.py, line 1)

In [67]:
for i in range(5):

SyntaxError: incomplete input (1925085379.py, line 1)

In [68]:
for i in rage(5):
    print(i**2, end = ' ')

NameError: name 'rage' is not defined

In [69]:
for i in range(5):
    print(i ** 2, end = ' ')

0 1 4 9 16 

In [70]:
for i in range(3, 15, 2):
    print(i, end=' ')

3 5 7 9 11 13 

In [71]:
l = ['a', 'b', 'c', 'd', 'e']

In [72]:
for _ in l:
    print(_)

a
b
c
d
e


In [73]:
s = "Python Trading"

In [74]:
for c in s:
    print(c + '|', end=' ')

P| y| t| h| o| n|  | T| r| a| d| i| n| g| 

In [75]:
i = 0 

while i < 5: 
    print(i**0.5, end=' ') 
    i += 1 

0.0 1.0 1.4142135623730951 1.7320508075688772 2.0 

In [76]:
lc = [i ** 2 for i in range(10)]

In [77]:
lc

[0, 1, 4, 9, 16, 25, 36, 49, 64, 81]

In [78]:
type(lc)

list

In [79]:
f = lambda x: math.cos(x) 

In [80]:
f(5)

0.28366218546322625

In [81]:
list(map(lambda x: math.cos(x), range(10)))

[1.0,
 0.5403023058681398,
 -0.4161468365471424,
 -0.9899924966004454,
 -0.6536436208636119,
 0.28366218546322625,
 0.960170286650366,
 0.7539022543433046,
 -0.14550003380861354,
 -0.9111302618846769]

In [82]:
def f(x):
    return math.exp(x)

In [83]:
f(5)

148.4131591025766

In [84]:
def f(*args): 
    for arg in args:
        print(arg)
    return None 

In [85]:
f(l)

['a', 'b', 'c', 'd', 'e']


In [86]:
f(l*)

SyntaxError: invalid syntax (2349715631.py, line 1)

In [87]:
f(*l)

a
b
c
d
e


In [88]:
import random

In [89]:
a = random.randint(0, 1000)

In [95]:
print(f'Random number is {a}')

Random number is 128


In [97]:
def number_decide(number): 
    if a < 10:
        return "Number is single digit."
    elif 10 <= a < 100: 
        return "Number is double digit."
    else: 
        return "Number is triple digit."

In [98]:
number_decide(a)

'Number is triple digit.'

In [99]:
import numpy as np


In [100]:
a = np.array(range(24))

In [101]:
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [102]:
b = a.reshape((4, 6))

In [103]:
b

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

In [104]:
c = a.reshape((2,3,4))

In [105]:
c

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [111]:
b = np.array(b, dtype=np.float64)

In [112]:
b

array([[ 0.,  1.,  2.,  3.,  4.,  5.],
       [ 6.,  7.,  8.,  9., 10., 11.],
       [12., 13., 14., 15., 16., 17.],
       [18., 19., 20., 21., 22., 23.]])

In [113]:
2*b

array([[ 0.,  2.,  4.,  6.,  8., 10.],
       [12., 14., 16., 18., 20., 22.],
       [24., 26., 28., 30., 32., 34.],
       [36., 38., 40., 42., 44., 46.]])

In [114]:
b ** 2

array([[  0.,   1.,   4.,   9.,  16.,  25.],
       [ 36.,  49.,  64.,  81., 100., 121.],
       [144., 169., 196., 225., 256., 289.],
       [324., 361., 400., 441., 484., 529.]])

In [115]:
f = lambda x: x**2 - 2*x + 0.5 

In [116]:
f(a)

array([  0.5,  -0.5,   0.5,   3.5,   8.5,  15.5,  24.5,  35.5,  48.5,
        63.5,  80.5,  99.5, 120.5, 143.5, 168.5, 195.5, 224.5, 255.5,
       288.5, 323.5, 360.5, 399.5, 440.5, 483.5])

In [117]:
a[2:6]

array([2, 3, 4, 5])

In [118]:
b[2. 4]

SyntaxError: invalid syntax. Perhaps you forgot a comma? (2292514335.py, line 1)

In [119]:
b[2, 4]

np.float64(16.0)

In [120]:
b[1:3, 2:4]

array([[ 8.,  9.],
       [14., 15.]])

In [121]:
b > 10 

array([[False, False, False, False, False, False],
       [False, False, False, False, False,  True],
       [ True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True]])

In [122]:
b[b > 10]

array([11., 12., 13., 14., 15., 16., 17., 18., 19., 20., 21., 22., 23.])

In [123]:
a.sum()

np.int64(276)

In [124]:
b.mean()

np.float64(11.5)

In [125]:
b.mean(axis=0)

array([ 9., 10., 11., 12., 13., 14.])

In [126]:
c.std()

np.float64(6.922186552431729)

In [127]:
b.mean(axis=1)

array([ 2.5,  8.5, 14.5, 20.5])